---
- name: Cert Management on BIG-IP
  hosts: all
  gather_facts: false
  connection: local

  tasks:

  - set_fact:
     provider:
      server: "{{inventory_hostname}}"
      server_port: "443"
      validate_certs: "False"

  - name: SSL cert upload
    bigip_ssl_certificate:
      provider: "{{provider}}"
      name: "demo_cert"
      content: "{{ lookup('file', cert) }}"

  - name: SSL cert upload
    bigip_ssl_key:
      provider: "{{provider}}"
      name: "demo_key"
      content: "{{ lookup('file', key) }}"

  - name: Create a client SSL profile with a cert/key/chain setting
    bigip_profile_client_ssl:
     provider: "{{provider}}"
     state: present
     name: demo_profile
     cert_key_chain:
      - cert: demo_cert
        key: demo_key

  - name: UPDATE A VIRTUAL SERVER
    bigip_virtual_server:
     provider: "{{provider}}"
     destination: "{{vip_ipaddr}}"
     port: 443
     profiles:
     - name: demo_profile
       context: client-side
