---
- name: Cert Management on BIG-IP
  hosts: all
  gather_facts: false
  connection: local

  tasks:

  - set_fact:
     provider:
      server: "{{inventory_hostname}}"
      server_port: "443"
      validate_certs: "False"

  - name: SSL cert upload
    bigip_ssl_certificate:
      provider: "{{provider}}"
      name: "{{cert}}"
      content: "{{ lookup('file', cert) }}"

  - name: SSL cert upload
    bigip_ssl_key:
      provider: "{{provider}}"
      name: "{{key}}"
      content: "{{ lookup('file', key) }}"

  - name: Create a client SSL profile with a cert/key/chain setting
    bigip_profile_client_ssl:
     provider: "{{provider}}"
     state: present
     name: "{{cert}}_{{key}}_profile"
     cert_key_chain:
      - cert: "{{cert}}"
        key: "{{key}}"

  - name: Create an LTM policy
    bigip_policy:
      provider: "{{provider}}"
      name: asm-policy

  - name: Import and activate ASM policy
    bigip_asm_policy:
      provider: "{{provider}}"
      name: Demo
      file: "asm_policy.xml"
      active: yes
      state: present

  - name: Replace a forward action with an ASM action
    bigip_policy_rule:
      provider: "{{provider}}"
      policy: asm-policy
      name: rule1
      actions:
      - type: enable
        asm_policy: Demo
        
  - name: UPDATE A VIRTUAL SERVER
    bigip_virtual_server:
     provider: "{{provider}}"
     name: "{{vip_name}}"
     profiles:
     - name: "{{cert}}_{{key}}_profile"
       context: client-side
     - http
     - websecurity
      policies:
      - asm-policy
