---
- name: Create JSON Payload
  hosts: bigips
  gather_facts: false
  connection: local

  tasks:

  - name: Build JSON payload
    template: src=http_as3.j2 dest=http_as3.json

  - name: Run command
    uri:
       url: "https://{{inventory_hostname}}{{uri}}"
       method: "{{method}}"
       #user: admin
       #password: admin
       validate_certs: no
       body: "{{(lookup('file','http_as3.json'))}}"
       body_format: json
