- name: Global LB
  hosts: localhost
  connection: local
  
  vars_files:
    - var.yml

  environment:
   F5_USER: "{{ username }}"
   F5_PASSWORD: "{{ password }}"
   F5_SERVER_PORT: "443"
   F5_VALIDATE_CERTS: "False"
    
  vars:
   datacenter_name: "/Common/San Jose"
   ltm1_server_name: "LTM1_Server"
   ltm2_server_name: "LTM2_Server"
   ltm2_vip: "{{ vip_name }}"
   dns_pool: "gtm_pool"
   dns_server_IPAddress: "10.192.73.219"

  tasks:

  - name: Create server
    bigip_gtm_server:
     server: "{{ dns_server_IPAddress }}"
     name: "{{ ltm2_server_name }}"
     datacenter: "{{datacenter_name}}"
     server_type: bigip
     link_discovery: enabled
     virtual_server_discovery: enabled
     devices:
       - {'name': 'server_1', 'address': "{{selfip_information[0].address}}"}  #Self-IP of LTM2
   
  - wait_for:
      timeout: 15
      
  - name: Add member to GTM pool
    bigip_gtm_pool:
     server: "{{ dns_server_IPAddress }}"
     name: "{{ dns_pool }}"
     type: a
     members:
     - server: "/Common/{{ ltm1_server_name }}"
       virtual_server: "/Common/{{ ltm1_vip }}"
     - server: "/Common/{{ ltm2_server_name }}"
       virtual_server: "/Common/{{ ltm2_vip }}"

  - name: Disable Virtual Server
    bigip_virtual_server:
      server: "{{ ltm1_IPAddress }}"
      name: "{{ ltm1_vip }}"
      state: "disabled"
