#Create the new LTM server (ltm2) and assign to existing DNS datacenter
#BIG-IP DNS now has visibility into all virtual servers on the ltm2, add the ltm2 virtual server to the existing dns pool
#Disable the virtual server on ltm1

- name: Global LB
  hosts: localhost
  connection: local
  
  vars_files:
    - var.yml

  environment:
   F5_USER: "{{ username }}"
   F5_PASSWORD: "{{ password }}"
   F5_SERVER_PORT: "443"
   F5_VALIDATE_CERTS: "False"
    
  vars:
   datacenter_name: "/Common/San Jose"
   ltm1_server_name: "LTM1_Server"
   ltm2_server_name: "LTM2_Server"
   ltm2_vip: "{{ vip_name }}"
   dns_pool: "gtm_pool"
   dns_server_IPAddress: "10.192.73.219"

  tasks:

  - name: Create LTM server
    bigip_gtm_server:
     server: "{{ dns_server_IPAddress }}"
     name: "{{ ltm2_server_name }}"
     datacenter: "{{datacenter_name}}"
     server_type: bigip
     link_discovery: enabled
     virtual_server_discovery: enabled
     devices:
       - {'name': 'server_1', 'address': "{{selfip_information[0].address}}"}  #Self-IP of LTM2 from var file
 
  #Wait for 20 seconds for GTM to grab all the configuration from the newly added LTM
  - wait_for:
      timeout: 20
      
  #Ideally here we should use bigip_gtm_pool_member so that we dont have to pass in all the pool members but only the ones
  #we want to add. There is an issue on gtm_pool_member due to which I am using this module as of now
  #ISSUE: https://github.com/F5Networks/f5-ansible/issues/716
  - name: Add LTM VIP to GTM pool
    bigip_gtm_pool:
     server: "{{ dns_server_IPAddress }}"
     name: "{{ dns_pool }}"
     type: a
     members:
     - server: "/Common/{{ ltm1_server_name }}"
       virtual_server: "/Common/{{ ltm1_vip }}"
     - server: "/Common/{{ ltm2_server_name }}"
       virtual_server: "/Common/{{ ltm2_vip }}"

  #Disable the Virtual Server on LTM1, this will casue all the traffic to now be directed to LTM2
  #Since we added LTM2 to the DNS pool in the above step
  - name: Disable Virtual Server
    bigip_virtual_server:
      server: "{{ ltm1_IPAddress }}"
      name: "{{ ltm1_vip }}"
      state: "disabled"
