- name: Onboard
  hosts: all
  connection: local
  gather_facts: false
   
  vars_files:
    - var.yml

  tasks:

  -name: Setting up provider values
   set_fact:
     provider:
      server: "{{inventory_hostname}}"
      server_port: "443"
      validate_certs: "False"
      
  #Onboard the BIG-IP (NTP/Hostname/SSHD/DNS)
  - name: Configure NTP server on BIG-IP
    bigip_device_ntp:
      provider: "{{provider}}"
      ntp_servers: "{{ ntp_servers }}"

  - name: Configure BIG-IP hostname
    bigip_hostname:
      provider: "{{provider}}"
      hostname: "{{ hostname }}"

  - name: Manage SSHD setting on BIG-IP
    bigip_device_sshd:
      provider: "{{provider}}"
      banner: "enabled"
      banner_text: " {{ banner_text }}"

  - name: Manage BIG-IP DNS settings
    bigip_device_dns:
     provider: "{{provider}}"
     name_servers: "{{ dns_servers }}"

    #Network the BIG-IP (VLANS/Self-IP configuration)
  - name: Configure VLANs on the BIG-IP
    bigip_vlan:
     provider: "{{provider}}"
     name: "{{ item.name }}"
     tag: "{{ item.tag }}"
     untagged_interface: "{{ item.interface }}"
    with_items: "{{ vlan_information }}"
    
  - name: Configure SELF-IPs on the BIG-IP
    bigip_selfip:
     provider: "{{provider}}"
     name: "{{ item.name }}"
     address: "{{ item.address }}"
     netmask: "{{ item.netmask }}"
     vlan: "{{ item.vlan }}"
     allow_service: "{{item.allow_service}}"
    with_items: "{{ selfip_information }}"
    
    #Deploy ASM policy
  - name: Create an LTM policy
    bigip_policy:
      provider: "{{provider}}"
      name: asm-policy

  - name: Import and activate ASM policy
    bigip_asm_policy:
      provider: "{{provider}}"
      name: Demo
      file: "asm_policy.xml"
      active: yes
      state: present
    
  - name: Replace a forward action with an ASM action
    bigip_policy_rule:
      provider: "{{provider}}"
      policy: asm-policy
      name: rule1
      actions:
      - type: enable
        asm_policy: Demo

  #Create VS/Pool/members
  - name: Create nodes
    bigip_node:
      provider: "{{provider}}"
      host: "{{item.host}}"
      name: "{{item.host}}"
    with_items: "{{pool_members}}"
  
  - name: Create pool
    bigip_pool:
      provider: "{{provider}}"
      state: "present"
      name: "http-pool"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
  
  - name: Add Pool members
    bigip_pool_member:
      provider: "{{provider}}"
      name: "{{item.host}}"
      host: "{{item.host}}"
      port: "{{item.port}}"
      pool: "http-pool"
    with_items: "{{pool_members}}"
  
    #Attach ASM profile to the virtual server amongst other configurations
  - name: Add Virtual Server
    bigip_virtual_server:
      provider: "{{provider}}"
      name: "{{vip_name}}"
      destination: "{{vip_ip}}"
      port: "{{vip_port}}"
      pool: "http-pool"
      snat: "Automap"
      profiles:
       - http
       - websecurity
      policies:
       - asm-policy
