- name: Create shell script
  hosts: localhost
  gather_facts: false

  vars_files:
    - var.yml

  tasks:

  #Create shell script to run the bigip_add command
  - name: Create shell script
    blockinfile:
     path: ./test.sh
     create: yes
     block: |
        #!/bin/bash
        /usr/bin/expect << EOF
        spawn /usr/local/bin/bigip_add "{{selfip_information[0].address}}"
        expect "Password:"
        send "default\r"
        expect "*Done*"
        EOF
        
  #Create ssh config file so that StrictHostKeyChecking is set to no 
  #For more details on why this is being done:
  #http://bencane.com/2013/07/22/ssh-disable-host-checking-for-scripts-automation/
  - name: Create config file
    lineinfile:
     dest: ./config
     create: yes
     line: "StrictHostKeyChecking no"

- name: Run gtm commands
  hosts: bigip-gtm
  gather_facts: false

  vars_files:
    - var.yml
    
  tasks:

  # Copy the files to the BIG-IP GTM
  - name: Copy file
    copy: src='config' dest='/root/.ssh/config'

  - name: Copy file
    copy: src='test.sh' dest='/tmp/test.sh'

  # Execute the bigip_add and big3d_install command
  - name: Execute shell
    command: sh /tmp/test.sh
    
  - name: Execute command
    command: /usr/local/bin/big3d_install "{{selfip_information[0].address}}"

 
